### ISSUE TITLE
Change Dockerfile to use Poetry

### ISSUE THREAD

**Issue by hisandan** [EthereumBogota/meetdapp-data-backend#2]
Dockerfile is using pip with requirements.txt instead of poetry

**Comment by RookieCol** [comment]
I'll, ill send the pr soon

**Comment by hisandan** [comment]
I just pull requested a simple version and that may work meanwhile

[https://github.com/EthereumBogota/meetdapp-data-backend/pull/3](https://github.com/EthereumBogota/meetdapp-data-backend/pull/3)

**Comment by RookieCol** [comment]
Thanks for reporting this issue! I took a look at the Dockerfile and noticed that the EXPOSE 5000 directive was outdated, which could confuse users trying to run the container.

To fix this, I updated the Dockerfile to reflect the correct port the container will be listening on, which is port 80. By using the command docker run -p 8080:80, users will be able to access the app on port 8080 of their host.

I also removed the EXPOSE 5000 directive, as it's not needed since the listening port is now documented with EXPOSE 80.

Additionally, I noticed there was a problem with the database connection, causing the app to hang and stop. To prevent this, I temporarily removed the database connection until it's properly fixed. This way, the app will work without interruptions while we address the issue.

Moreover, I added a proposal to the README, providing more information on how to set up the image  correctly and avoid future issues.

Thanks again for your contribution to the project and for identifying these problems. If you have any other questions or concerns, feel free to let me know.

I'll close this issue once the changes have been reviewed and merged.
